"""Criar tabelas iniciais

Revision ID: 5ffb16c40e4d
Revises:
Create Date: 2026-08-22 16:01:50.880244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffb16c40e4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsi_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('intervalo', sa.String(length=10), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rsi_status', sa.String(length=20), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsi_data')
    # ### end Alembic commands ###
